<?php

declare(strict_types=1);

namespace App\Controllers\Admin;

use App\Services\Reports\CycleReportService;
use App\Storage\LocalFileStorage;
use App\Support\Flash;
use App\Support\View;
use RuntimeException;

final class CycleReportController extends BaseAdminController
{
    public function index(): string
    {
        $this->requireAdmin();
        $cycle = $this->requireCurrentCycle();
        $summary = $this->summary((int) $cycle['id']);
        $blockers = $this->blockers((int) $cycle['id']);

        $blockerHtml = '';
        foreach ($blockers as $label=>$count) {
            if ($count > 0) {
                $blockerHtml .= '<li><strong>' . View::e($label) . ':</strong> ' . (int) $count . '</li>';
            }
        }

        $closeHtml = $blockerHtml === ''
            ? '<form method="post" action="/admin/cycle-report/complete">' . View::csrfField()
                . '<button type="submit">Mark cycle complete</button></form>'
            : '<div class="notice"><strong>Cycle cannot be completed yet.</strong><ul>' . $blockerHtml . '</ul></div>';

        $exportRows = '';
        $stmt = $this->pdo->prepare(
            "SELECT ce.*, fo.original_filename, u.display_name AS generated_by
             FROM cycle_exports ce
             JOIN file_objects fo ON fo.id = ce.file_id
             JOIN users u ON u.id = ce.generated_by_user_id
             WHERE ce.cycle_id = ?
             ORDER BY ce.generated_at DESC"
        );
        $stmt->execute([(int) $cycle['id']]);

        foreach ($stmt->fetchAll() as $row) {
            $exportRows .= '<tr><td>' . View::e(ucwords(str_replace('_',' ',$row['export_type']))) . '</td>'
                . '<td>' . View::e($row['original_filename']) . '</td>'
                . '<td>' . View::e($row['generated_by']) . '</td>'
                . '<td>' . View::e(date('M j, Y g:i a', strtotime((string)$row['generated_at']))) . '</td>'
                . '<td><a class="button secondary small" href="/admin/cycle-report/exports/' . (int)$row['id'] . '">Download</a></td></tr>';
        }
        if ($exportRows === '') {
            $exportRows = '<tr><td colspan="5">No cycle exports generated yet.</td></tr>';
        }

        $body = Flash::render()
            . '<div class="page-header"><div><h1>Cycle close & reporting</h1><p>Review completion status, generate structured exports, and close the academic cycle when operational work is finished.</p></div></div>'
            . '<div class="grid">'
            . '<section class="stat"><span>Awards</span><strong>' . (int)$summary['awards'] . '</strong></section>'
            . '<section class="stat"><span>Total awarded</span><strong>' . View::money($summary['total_awarded']) . '</strong></section>'
            . '<section class="stat"><span>Recipients</span><strong>' . (int)$summary['recipients'] . '</strong></section>'
            . '<section class="stat"><span>Thank-yous submitted</span><strong>' . (int)$summary['thank_yous'] . '</strong></section>'
            . '<section class="stat"><span>Thank-yous outstanding</span><strong>' . (int)$summary['thank_yous_outstanding'] . '</strong></section>'
            . '</div>'
            . '<section class="card" style="margin-top:1rem"><h2>Generate export</h2>'
            . '<form method="post" action="/admin/cycle-report/export">' . View::csrfField()
            . '<div class="actions">'
            . $this->exportButton('awards','Awards')
            . $this->exportButton('allocations','Allocations')
            . $this->exportButton('recipients','Recipients')
            . $this->exportButton('thank_yous','Thank-yous')
            . $this->exportButton('audit','Audit log')
            . '</div></form></section>'
            . '<section class="card" style="margin-top:1rem"><h2>Generated exports</h2><div class="table-wrap"><table>'
            . '<thead><tr><th>Type</th><th>File</th><th>Generated by</th><th>Date</th><th>Download</th></tr></thead><tbody>'
            . $exportRows . '</tbody></table></div></section>'
            . '<section class="card" style="margin-top:1rem"><h2>Complete cycle</h2>'
            . '<p>Outstanding thank-you letters are reported above but do not block cycle completion because the deadline is intentionally soft. Program review, unresolved award processing, pending distribution requests, and active mail jobs do block completion.</p>'
            . $closeHtml . '</section>';

        return $this->render('Cycle close & reporting', $body, $cycle);
    }

    public function export(): never
    {
        $this->requireAdmin();
        $this->requirePost();
        $cycle = $this->requireCurrentCycle();
        $type = (string) ($_POST['export_type'] ?? '');

        try {
            $id = (new CycleReportService($this->pdo, new LocalFileStorage()))
                ->generate((int)$cycle['id'], (int)$this->auth->userId(), $type);

            $this->audit('cycle.export_generated','cycle_export',$id,(int)$cycle['id'],null,['type'=>$type]);
            Flash::success(ucwords(str_replace('_',' ',$type)) . ' export generated.');
        } catch (\Throwable $e) {
            Flash::error($e->getMessage());
        }

        $this->redirect('/admin/cycle-report');
    }

    public function download(array $params): never
    {
        $this->requireAdmin();
        $cycle = $this->requireCurrentCycle();
        $id = (int)($params['id'] ?? 0);

        $stmt = $this->pdo->prepare(
            "SELECT fo.*
             FROM cycle_exports ce
             JOIN file_objects fo ON fo.id = ce.file_id
             WHERE ce.id = ? AND ce.cycle_id = ?"
        );
        $stmt->execute([$id,(int)$cycle['id']]);
        $file = $stmt->fetch();

        if (!$file) {
            http_response_code(404);
            exit('Export not found.');
        }

        $path = (new LocalFileStorage())->path((string)$file['storage_key']);
        header('Content-Type: ' . $file['mime_type']);
        header('Content-Length: ' . (string)filesize($path));
        header('Content-Disposition: attachment; filename="' . str_replace('"','',(string)$file['original_filename']) . '"');
        header('X-Content-Type-Options: nosniff');
        readfile($path);
        exit;
    }

    public function complete(): never
    {
        $this->requireAdmin();
        $this->requirePost();
        $cycle = $this->requireCurrentCycle();

        try {
            $blockers = $this->blockers((int)$cycle['id']);
            $remaining = array_filter($blockers, static fn(int $count): bool => $count > 0);

            if ($remaining !== []) {
                throw new RuntimeException('The cycle still has operational blockers and cannot be completed.');
            }

            $this->pdo->prepare(
                "UPDATE academic_cycles
                 SET status = 'complete', completed_at = NOW(), completed_by_user_id = ?
                 WHERE id = ?"
            )->execute([$this->auth->userId(),$cycle['id']]);

            $this->audit('cycle.completed','academic_cycle',(int)$cycle['id'],(int)$cycle['id']);
            Flash::success('Academic cycle marked complete.');
        } catch (\Throwable $e) {
            Flash::error($e->getMessage());
        }

        $this->redirect('/admin/cycle-report');
    }

    private function summary(int $cycleId): array
    {
        $stmt = $this->pdo->prepare(
            "SELECT
                COUNT(a.id) AS awards,
                COALESCE(SUM(CASE WHEN a.status <> 'cancelled' THEN a.total_amount ELSE 0 END),0) AS total_awarded,
                COUNT(DISTINCT CASE WHEN a.status <> 'cancelled' THEN a.student_id END) AS recipients,
                COUNT(DISTINCT ts.id) AS thank_yous,
                COUNT(DISTINCT CASE WHEN a.status = 'notified' AND ts.id IS NULL THEN a.id END) AS thank_yous_outstanding
             FROM awards a
             LEFT JOIN thank_you_submissions ts ON ts.award_id = a.id
             WHERE a.cycle_id = ?"
        );
        $stmt->execute([$cycleId]);

        return $stmt->fetch() ?: [
            'awards'=>0,'total_awarded'=>0,'recipients'=>0,'thank_yous'=>0,'thank_yous_outstanding'=>0,
        ];
    }

    private function blockers(int $cycleId): array
    {
        $queries = [
            'Review units still open' => [
                "SELECT COUNT(*) FROM cycle_review_units
                 WHERE cycle_id = ? AND status NOT IN ('submitted','resubmitted','closed')", [$cycleId]
            ],
            'Awards not finalized/notified' => [
                "SELECT COUNT(*) FROM awards
                 WHERE cycle_id = ? AND status IN ('draft','pending_verification','approved','ready_to_notify')", [$cycleId]
            ],
            'Pending distribution requests' => [
                "SELECT COUNT(*)
                 FROM distribution_requests dr
                 JOIN awards a ON a.id = dr.award_id
                 WHERE a.cycle_id = ? AND dr.status = 'pending'", [$cycleId]
            ],
            'Mail jobs still queued/processing' => [
                "SELECT COUNT(*)
                 FROM jobs j
                 WHERE j.status IN ('queued','processing')
                   AND (
                     (j.job_type = 'award_notification' AND EXISTS (
                        SELECT 1 FROM award_notifications an
                        JOIN awards a ON a.id = an.award_id
                        WHERE an.id = JSON_UNQUOTE(JSON_EXTRACT(j.payload_json,'$.notification_id'))
                          AND a.cycle_id = ?
                     ))
                     OR
                     (j.job_type = 'thank_you_reminder' AND EXISTS (
                        SELECT 1 FROM thank_you_reminder_notifications tr
                        JOIN awards a ON a.id = tr.award_id
                        WHERE tr.id = JSON_UNQUOTE(JSON_EXTRACT(j.payload_json,'$.notification_id'))
                          AND a.cycle_id = ?
                     ))
                   )", [$cycleId,$cycleId]
            ],
        ];

        $result = [];
        foreach ($queries as $label=>[$sql,$params]) {
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute($params);
            $result[$label] = (int)$stmt->fetchColumn();
        }

        return $result;
    }

    private function exportButton(string $value, string $label): string
    {
        return '<button class="secondary" type="submit" name="export_type" value="' . View::e($value) . '">' . View::e($label) . '</button>';
    }
}
