CREATE TABLE annual_authority_imports (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cycle_id BIGINT UNSIGNED NOT NULL,
    file_id BIGINT UNSIGNED NOT NULL,
    filename VARCHAR(255) NOT NULL,
    status ENUM('processing','completed','partial_failure','failed') NOT NULL DEFAULT 'processing',
    row_count INT UNSIGNED NOT NULL DEFAULT 0,
    imported_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_scholarship_count INT UNSIGNED NOT NULL DEFAULT 0,
    updated_scholarship_count INT UNSIGNED NOT NULL DEFAULT 0,
    warning_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_summary TEXT NULL,
    imported_by_user_id BIGINT UNSIGNED NOT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_authority_import_cycle FOREIGN KEY (cycle_id) REFERENCES academic_cycles(id),
    CONSTRAINT fk_authority_import_file FOREIGN KEY (file_id) REFERENCES file_objects(id),
    CONSTRAINT fk_authority_import_user FOREIGN KEY (imported_by_user_id) REFERENCES users(id),
    KEY idx_authority_import_cycle (cycle_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE cycle_scholarships
    ADD COLUMN award_category ENUM('scholarship','spring_award') NOT NULL DEFAULT 'scholarship' AFTER suggested_new_award_amount,
    ADD COLUMN award_plan_text VARCHAR(500) NULL AFTER award_category,
    ADD COLUMN source_department_area VARCHAR(255) NULL AFTER award_plan_text,
    ADD COLUMN source_student_level VARCHAR(100) NULL AFTER source_department_area,
    ADD COLUMN authority_note VARCHAR(500) NULL AFTER source_student_level,
    ADD COLUMN annual_authority_import_id BIGINT UNSIGNED NULL AFTER authority_note,
    ADD CONSTRAINT fk_cycle_sch_authority_import FOREIGN KEY (annual_authority_import_id) REFERENCES annual_authority_imports(id);

CREATE TABLE cycle_fund_financial_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    annual_authority_import_id BIGINT UNSIGNED NOT NULL,
    cycle_scholarship_id BIGINT UNSIGNED NOT NULL,
    source_sheet VARCHAR(255) NOT NULL,
    source_row_number INT UNSIGNED NOT NULL,
    endowed_invested TINYINT(1) NULL,
    donor_report_required TINYINT(1) NULL,
    fund_class VARCHAR(255) NULL,
    investment_pool VARCHAR(255) NULL,
    spendable_cash DECIMAL(14,2) NULL,
    spendable_investment DECIMAL(14,2) NULL,
    endowed_cash DECIMAL(14,2) NULL,
    endowed_investment DECIMAL(14,2) NULL,
    account_balance DECIMAL(14,2) NULL,
    next_fy_payout_projection DECIMAL(14,2) NULL,
    total_expenses DECIMAL(14,2) NULL,
    prior_year_total_expenses DECIMAL(14,2) NULL,
    ui_expenses DECIMAL(14,2) NULL,
    prior_year_ui_expenses DECIMAL(14,2) NULL,
    donor_report_recipient TEXT NULL,
    donor_report_contact VARCHAR(255) NULL,
    uica_comments TEXT NULL,
    summarized_donor_intent TEXT NULL,
    source_values_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fund_snapshot_import FOREIGN KEY (annual_authority_import_id) REFERENCES annual_authority_imports(id) ON DELETE CASCADE,
    CONSTRAINT fk_fund_snapshot_cycle_sch FOREIGN KEY (cycle_scholarship_id) REFERENCES cycle_scholarships(id) ON DELETE CASCADE,
    UNIQUE KEY uq_fund_snapshot_import_scholarship (annual_authority_import_id, cycle_scholarship_id),
    KEY idx_fund_snapshot_cycle_sch (cycle_scholarship_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
