ALTER TABLE scholarships
    DROP INDEX uq_scholarship_uica,
    ADD COLUMN source_record_key VARCHAR(500) NULL AFTER uica_account_number,
    ADD UNIQUE KEY uq_scholarship_source_record (source_record_key),
    ADD KEY idx_scholarship_uica (uica_account_number);

ALTER TABLE cycle_fund_financial_snapshots
    ADD COLUMN uica_top_giver VARCHAR(255) NULL AFTER source_row_number,
    ADD COLUMN dormant VARCHAR(100) NULL AFTER uica_top_giver,
    ADD COLUMN underutilized VARCHAR(100) NULL AFTER dormant,
    ADD COLUMN endowment_code VARCHAR(100) NULL AFTER underutilized,
    ADD COLUMN college_code VARCHAR(100) NULL AFTER endowment_code,
    ADD COLUMN department_code VARCHAR(100) NULL AFTER college_code,
    ADD COLUMN area_code VARCHAR(100) NULL AFTER department_code,
    ADD COLUMN expense_code VARCHAR(255) NULL AFTER fund_class,
    ADD COLUMN ui_hospital_org VARCHAR(100) NULL AFTER expense_code,
    ADD COLUMN sport VARCHAR(100) NULL AFTER ui_hospital_org,
    ADD COLUMN fund_start_date DATE NULL AFTER sport,
    ADD COLUMN administrator_name VARCHAR(255) NULL AFTER fund_start_date,
    ADD COLUMN dni_value VARCHAR(100) NULL AFTER administrator_name,
    ADD COLUMN memorial_honorary VARCHAR(100) NULL AFTER donor_report_required,
    ADD COLUMN geo VARCHAR(100) NULL AFTER memorial_honorary,
    ADD COLUMN fund_status VARCHAR(100) NULL AFTER geo,
    ADD COLUMN pledge DECIMAL(14,2) NULL AFTER endowed_investment,
    ADD COLUMN illiquids DECIMAL(14,2) NULL AFTER pledge,
    ADD COLUMN gifts DECIMAL(14,2) NULL AFTER account_balance,
    ADD COLUMN pledge_payments DECIMAL(14,2) NULL AFTER gifts,
    ADD COLUMN new_pledges DECIMAL(14,2) NULL AFTER pledge_payments,
    ADD COLUMN other_income DECIMAL(14,2) NULL AFTER new_pledges,
    ADD COLUMN appreciation DECIMAL(14,2) NULL AFTER other_income,
    ADD COLUMN interest_income DECIMAL(14,2) NULL AFTER appreciation,
    ADD COLUMN adjustments DECIMAL(14,2) NULL AFTER interest_income,
    ADD COLUMN last_ui_expense_date DATE NULL AFTER prior_year_ui_expenses,
    ADD COLUMN prior_fy_payout_projection DECIMAL(14,2) NULL AFTER last_ui_expense_date,
    ADD COLUMN transfer_in DECIMAL(14,2) NULL AFTER next_fy_payout_projection,
    ADD COLUMN transfer_out DECIMAL(14,2) NULL AFTER transfer_in,
    ADD COLUMN net_transfers DECIMAL(14,2) NULL AFTER transfer_out,
    ADD COLUMN historical_gift_value DECIMAL(14,2) NULL AFTER net_transfers,
    ADD COLUMN percent_above_hgv DECIMAL(12,6) NULL AFTER historical_gift_value;

CREATE TABLE annual_fund_source_rows (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    annual_authority_import_id BIGINT UNSIGNED NOT NULL,
    scholarship_id BIGINT UNSIGNED NULL,
    source_sheet VARCHAR(255) NOT NULL,
    source_kind ENUM('simplified','all_data','uica_master') NOT NULL,
    source_row_number INT UNSIGNED NOT NULL,
    fund_id VARCHAR(100) NULL,
    fund_name VARCHAR(255) NULL,
    source_values_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fund_source_import FOREIGN KEY (annual_authority_import_id) REFERENCES annual_authority_imports(id) ON DELETE CASCADE,
    CONSTRAINT fk_fund_source_scholarship FOREIGN KEY (scholarship_id) REFERENCES scholarships(id),
    UNIQUE KEY uq_fund_source_row (annual_authority_import_id, source_sheet, source_row_number),
    KEY idx_fund_source_scholarship (scholarship_id),
    KEY idx_fund_source_fund (fund_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
